/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saimon
 */
public class livrosView extends javax.swing.JInternalFrame {

    /**
     * Creates new form livrosView
     */
    public livrosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        addCliente = new JLabel();
        JLabel jLabel9 = new JLabel();
        JPanel jPanel3 = new JPanel();
        PanelClientes = new JPanel();
        JScrollPane jScrollPane1 = new JScrollPane();
        tableClientes = new JTable();
        JPanel formClientes = new JPanel();
        JLabel jLabel3 = new JLabel();
        getPesqNome = new JTextField();
        JSeparator jSeparator1 = new JSeparator();
        jLabel4 = new JLabel();
        getNomeCliente = new JTextField();
        JLabel jLabel5 = new JLabel();
        getTelefoneCliente = new JTextField();
        JLabel jLabel6 = new JLabel();
        getEmailCliente = new JTextField();
        JLabel jLabel7 = new JLabel();
        getCPFCliente = new JTextField();
        JLabel jLabel8 = new JLabel();
        getEnderecoCliente = new JTextField();
        JLabel jLabel10 = new JLabel();
        idClienteField = new JTextField();
        consultar = new JButton();

        jPanel1.setBackground(new Color(0, 102, 102));

        jLabel1.setFont(new Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setText("Clientes");

        jLabel2.setIcon(new ImageIcon(getClass().getResource("/Search_1.png"))); // NOI18N

        addCliente.setIcon(new ImageIcon(getClass().getResource("/add user1.png"))); // NOI18N
        addCliente.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                addClienteMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new ImageIcon(getClass().getResource("/delete-user-icon-1.png"))); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addComponent(addCliente)
                .addGap(45, 45, 45)
                .addComponent(jLabel9)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCliente, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new Color(204, 204, 204));

        PanelClientes.setBackground(new Color(255, 255, 255));
        PanelClientes.setBorder(BorderFactory.createEtchedBorder());

        tableClientes.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "CPF", "Telefone", "Email", "Endereço", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClientes.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tableClientes);

        GroupLayout PanelClientesLayout = new GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(PanelClientesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING)
        );
        PanelClientesLayout.setVerticalGroup(PanelClientesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        formClientes.setBackground(new Color(255, 255, 255));
        formClientes.setBorder(BorderFactory.createEtchedBorder());

        jLabel3.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Buscando pelo livro:");

        getPesqNome.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                getPesqNomeKeyReleased(evt);
            }
        });

        jSeparator1.setForeground(new Color(102, 102, 102));

        jLabel4.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Titulo:");

        jLabel5.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Autor:");

        jLabel6.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Editora:");

        jLabel7.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Numero de paginas:");

        jLabel8.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ano de publicação:");

        jLabel10.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("idLivro:");

        consultar.setText("Consultar");
        consultar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        GroupLayout formClientesLayout = new GroupLayout(formClientes);
        formClientes.setLayout(formClientesLayout);
        formClientesLayout.setHorizontalGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, GroupLayout.Alignment.TRAILING)
            .addGroup(formClientesLayout.createSequentialGroup()
                .addGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(formClientesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(formClientesLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(getEnderecoCliente, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE))
                            .addGroup(formClientesLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idClienteField, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(consultar, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE))
                            .addGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addGroup(GroupLayout.Alignment.LEADING, formClientesLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(getNomeCliente, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(getCPFCliente, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE))
                                .addGroup(GroupLayout.Alignment.LEADING, formClientesLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(getTelefoneCliente, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(getEmailCliente, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(formClientesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getPesqNome, GroupLayout.PREFERRED_SIZE, 298, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formClientesLayout.setVerticalGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(formClientesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(getPesqNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idClienteField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(getNomeCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(getCPFCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(getTelefoneCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(getEmailCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formClientesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(getEnderecoCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(formClientes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelClientes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(formClientes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelClientes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClienteMouseClicked(MouseEvent evt) {//GEN-FIRST:event_addClienteMouseClicked
        // TODO add your handling code here:
        try {
            cliente cliente = new cliente();

            cliente.setNomeCliente(getNomeCliente.getText());
            cliente.setCpf(getCPFCliente.getText());
            cliente.setTelefone(getTelefoneCliente.getText());
            cliente.setEmail(getEmailCliente.getText());
            cliente.setEndereco(getEnderecoCliente.getText());

            clienteControl.save(cliente);
            JOptionPane.showMessageDialog(rootPane, "cliente salvo com sucesso");
            getNomeCliente.setText(null);
            getEmailCliente.setText(null);
            getCPFCliente.setText(null);
            getTelefoneCliente.setText(null);
            getEnderecoCliente.setText(null);

            loadclientes();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao adicionar um cliente");
        }
    }//GEN-LAST:event_addClienteMouseClicked

    private void getPesqNomeKeyReleased(KeyEvent evt) {//GEN-FIRST:event_getPesqNomeKeyReleased
        // TODO add your handling code here:
        PesquisaClientes();
    }//GEN-LAST:event_getPesqNomeKeyReleased

    private void consultarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        consultar();
    }//GEN-LAST:event_consultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    JPanel PanelClientes;
    JLabel addCliente;
    JButton consultar;
    JTextField getCPFCliente;
    JTextField getEmailCliente;
    JTextField getEnderecoCliente;
    JTextField getNomeCliente;
    JTextField getPesqNome;
    JTextField getTelefoneCliente;
    JTextField idClienteField;
    JLabel jLabel4;
    JTable tableClientes;
    // End of variables declaration//GEN-END:variables
}
