/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.livroController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import model.livro;
import util.ButtonColumnCellRender;
import util.tableModelLivros;
import view.clienteView;

/**
 *
 * @author Saimon
 */
public final class telaPrincipal extends javax.swing.JFrame {

    livroController livroControll;
    tableModelLivros livrosModel;

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();

        decorateTableLivros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panellivros = new JPanel();
        JScrollPane jScrollPane2 = new JScrollPane();
        tableLivros = new JTable();
        JPanel jPanel1 = new JPanel();
        JLabel systemTitle = new JLabel();
        JLabel jLabel2 = new JLabel();
        JPanel jPanel2 = new JPanel();
        registerLivro = new JLabel();
        JLabel jLabel1 = new JLabel();
        clientes = new JButton();
        desktop = new JDesktopPane();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();

        Panellivros.setBackground(new Color(255, 255, 255));

        tableLivros.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Ano de publicação", "Editora", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLivros.setFillsViewportHeight(true);
        tableLivros.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tableLivrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableLivros);

        GroupLayout PanellivrosLayout = new GroupLayout(Panellivros);
        Panellivros.setLayout(PanellivrosLayout);
        PanellivrosLayout.setHorizontalGroup(PanellivrosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        PanellivrosLayout.setVerticalGroup(PanellivrosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(PanellivrosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 403, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(0, 102, 102));

        systemTitle.setFont(new Font("Segoe UI", 1, 36)); // NOI18N
        systemTitle.setForeground(new Color(255, 255, 255));
        systemTitle.setText("Controle de atendimento");

        jLabel2.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setText("Sistema de gerenciamento da biblioteca");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(systemTitle, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(systemTitle)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setBorder(BorderFactory.createEtchedBorder());

        registerLivro.setIcon(new ImageIcon(getClass().getResource("/books_1.png"))); // NOI18N
        registerLivro.setCursor(new Cursor(Cursor.HAND_CURSOR));
        registerLivro.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                registerLivroMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/borrowBook.png"))); // NOI18N
        jLabel1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        clientes.setIcon(new ImageIcon(getClass().getResource("/users_1.png"))); // NOI18N
        clientes.setBorder(null);
        clientes.setBorderPainted(false);
        clientes.setCursor(new Cursor(Cursor.HAND_CURSOR));
        clientes.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(clientes)
                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addComponent(registerLivro, GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, GroupLayout.Alignment.LEADING)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(clientes)
                .addGap(37, 37, 37)
                .addComponent(registerLivro)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktop.setBackground(new Color(255, 255, 255));
        desktop.setBorder(BorderFactory.createEtchedBorder());
        desktop.setPreferredSize(new Dimension(617, 471));

        jLabel3.setBackground(new Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/fundo vazio.png"))); // NOI18N
        jLabel3.setToolTipText("");

        jLabel4.setFont(new Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("BEM VINDO");

        desktop.setLayer(jLabel3, JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel4, JLayeredPane.DEFAULT_LAYER);

        GroupLayout desktopLayout = new GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(desktopLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(desktopLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(213, 213, 213))
        );
        desktopLayout.setVerticalGroup(desktopLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(desktop, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerLivroMouseClicked(MouseEvent evt) {//GEN-FIRST:event_registerLivroMouseClicked
        // TODO add your handling code here:
        cadastroLivro livro = new cadastroLivro(this, rootPaneCheckingEnabled);
        livro.setVisible(true);

        livro.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadlivros();
            }
        });
    }//GEN-LAST:event_registerLivroMouseClicked

    private void jLabel1MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        emprestimoView emprestimo = new emprestimoView(this, rootPaneCheckingEnabled);
        emprestimo.setVisible(true);

        emprestimo.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
//                loadclientes();
            }
        });
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tableLivrosMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tableLivrosMouseClicked
//        // TODO add your handling code here:
//        int rowIndex = tableClientes.rowAtPoint(evt.getPoint());
//        int columnIndex = tableClientes.columnAtPoint(evt.getPoint());
//        livro livro = livrosModel.getlivros().get(rowIndex);
//
//
//        switch (columnIndex) {
//            case 3:
////                cadastroCliente updateCliente = new cadastroCliente(this, rootPaneCheckingEnabled);;
////                updateCliente.setVisible(true);
////
////                List<cliente> listaClientes = clienteControl.getAll();
////                cliente clienteUp = clienteControl.getOne(getCol);
////
////                for (int i = 0; i < listaClientes.size(); i++) {
////                    if (clienteUp == listaClientes.get(i)) {
////                        clienteControl.update(cliente);
////                    } else {
////                        clienteControl.save(cliente);
////                    }
////                }
//
//                break;
//
//            case 4:
//                livroControll.remove(livro.getIdLivro(), livro.getIdSecao());
//                livrosModel.getlivros().remove(livro);
//                break;
//        }
    }//GEN-LAST:event_tableLivrosMouseClicked

    private void clientesActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
        clienteView Screen = new clienteView();
        Screen.setVisible(true);
        desktop.remove(jLabel3);
        desktop.remove(jLabel4);
        
        desktop.add(Screen);
        System.out.println("click action");
    }//GEN-LAST:event_clientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JPanel Panellivros;
    JButton clientes;
    JDesktopPane desktop;
    JLabel jLabel3;
    JLabel jLabel4;
    JLabel registerLivro;
    JTable tableLivros;
    // End of variables declaration//GEN-END:variables

    //CONFIGURANDO OS CLIENTES
//CONFIGURANDO OS livroS
    public void decorateTableLivros() {
        tableLivros.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tableLivros.getTableHeader().setBackground(new Color(0, 102, 102));
        tableLivros.getTableHeader().setForeground(new Color(255, 255, 255));

        tableLivros.getAutoCreateRowSorter();

        tableLivros.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRender("excluir"));
    }

    public void loadlivros() {
        List<livro> livros = livroControll.getAll();
        livrosModel.setlivros(livros);

//        showTablelivros(!livros.isEmpty());
    }

//    private void showTablelivros(boolean haslivros) {
//        if (haslivros) {
//            if (PanelVazio.isVisible()) {
//                PanelVazio.setVisible(false);
//                PanelPrincipal.remove(PanelVazio);
//            }
//            PanelPrincipal.add(Panellivros);
//            Panellivros.setVisible(true);
//            Panellivros.setSize(PanelPrincipal.getWidth(), PanelPrincipal.getHeight());
//        } else {
//            if (Panellivros.isVisible()) {
//                Panellivros.setVisible(false);
//                PanelPrincipal.remove(Panellivros);
//            }
//            PanelPrincipal.add(PanelVazio);
//            PanelVazio.setVisible(true);
//            PanelVazio.setSize(PanelPrincipal.getWidth(), PanelPrincipal.getHeight());
//        }
//    }
    //CONFIGURANDO OS LIVROS
}
